/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReportBarang.java
 *
 * Created on 06 Apr 13, 23:05:05
 */

package amimarketaplikasi.GUI;

import amimarketaplikasi.Method.BarangControl;
import amimarketaplikasi.Method.ReportControl;
import amimarketaplikasi.entity.EntitasBarang;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ONE-System
 */
public class ReportBarang extends javax.swing.JFrame {

    /** Creates new form ReportBarang */
    public ReportBarang() {
       
        initComponents();
        isiCombo();
    }

    private void isiCombo(){
        listBarang=bc.tampilSatuan();
        if(listBarang.isEmpty()){
            cmbSatuan.setSelectedItem("");
        } else {
            for(int a=0;a<listBarang.size();a++){
                cmbSatuan.addItem(listBarang.get(a).getSatuan());
            }

        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        cmbSatuan = new javax.swing.JComboBox();
        optSemua = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        optSatuan = new javax.swing.JRadioButton();
        btnCetak = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cetak Barang");
        setResizable(false);

        jLayeredPane1.setBackground(new java.awt.Color(204, 255, 255));

        cmbSatuan.setBounds(150, 100, 210, 20);
        jLayeredPane1.add(cmbSatuan, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(optSemua);
        optSemua.setText("Semua Data");
        optSemua.setBounds(20, 60, 83, 23);
        jLayeredPane1.add(optSemua, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setText("Laporan Barang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel1.setBounds(0, 0, 380, 50);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(optSatuan);
        optSatuan.setText("Berdasarkan Satuan");
        optSatuan.setBounds(20, 100, 130, 23);
        jLayeredPane1.add(optSatuan, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Print.png"))); // NOI18N
        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        btnCetak.setBounds(150, 140, 100, 25);
        jLayeredPane1.add(btnCetak, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Keluar2.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setBounds(260, 140, 100, 25);
        jLayeredPane1.add(btnKeluar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-385)/2, (screenSize.height-225)/2, 385, 225);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        if(optSemua.isSelected()){
            rc.cetakSeleruhBarang();
        } else if(optSatuan.isSelected()){
            rc.cetakPerSatuan(cmbSatuan.getSelectedItem().toString());           
        } else{
            JOptionPane.showMessageDialog(null, "Pilih kriteria cetak barang");
        }
        
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                new ReportBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnKeluar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbSatuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton optSatuan;
    private javax.swing.JRadioButton optSemua;
    // End of variables declaration//GEN-END:variables

ReportControl rc=new ReportControl();
BarangControl bc=new BarangControl();
EntitasBarang eb=new EntitasBarang();
List <EntitasBarang> listBarang=new ArrayList<EntitasBarang>();
}
