/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amimarketaplikasi.GUI;

import amimarketaplikasi.Method.KasirControl;
import amimarketaplikasi.entity.EntitasKasir;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Disca Amelia
 */
public class frmKasir extends javax.swing.JFrame {
    int x=0;
        private DefaultTableModel model;
        KasirControl bc=new KasirControl();
        EntitasKasir eb=new EntitasKasir();
        List <EntitasKasir> listKasir =new ArrayList <EntitasKasir>();

    /**
     * Creates new form frmKasir
     */
    public frmKasir(java.awt.Frame parent, boolean modal) {
        
        initComponents();
        bersih();
        siapIsi(false);
        tombolNormal();
        buatTabel();
        showTabel();
        setLocationRelativeTo(null);
    }
    
    
     private void bersih(){
        fieldIDKasir.setText(null);
        fieldNamaKasir.setText(null);
        fieldAlamatKasir.setText(null);
        fieldUsernameKasir.setText(null);
        fieldPasswordKasir.setText(null);
    }

    private void siapIsi(boolean a){
        fieldIDKasir.setEnabled(a);
        fieldNamaKasir.setEnabled(a);
        fieldAlamatKasir.setEnabled(a);
        fieldUsernameKasir.setEnabled(a);
        fieldPasswordKasir.setEnabled(a);
    }
    
    private void tombolNormal(){
        buttonTambahKasir.setEnabled(true);
        buttonSimpanKasir.setEnabled(false);
        buttonHapusKair.setEnabled(false);
        buttonEditKasir.setEnabled(false);
        buttonKeluarKasir.setEnabled(true);
        cariKasir.setEnabled(true);
    }

    private void buatTabel(){
        model=new DefaultTableModel();
        model.addColumn("ID Kasir");
        model.addColumn("Nama");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Alamat");
        tableKasir.setModel(model);
    }
    
    private void showTabel (){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();    
        listKasir.clear();        
        listKasir =bc.tampil();        
        for(x=0;x<listKasir.size();x++){
            Object[] data=new Object[6];
            data[0]=listKasir.get(x).getId_kasir();
            data[1]=listKasir.get(x).getNama_kasir();
            data[2]=listKasir.get(x).getUsername();
            data[3]=listKasir.get(x).getPassword();
            data[4]=listKasir.get(x).getAlamat();
            model.addRow(data);            
        }        
    }

    private void setcexbox(JTable tabel, TableColumn colm){
           JCheckBox checkBox=new JCheckBox("setuju");
           colm.setCellEditor(new DefaultCellEditor(checkBox));
    }
    
    private void getData (){
        List logKasir = new ArrayList();
        
        
    }

    private void buatId_Kasir(){
        listKasir = bc.tampil();
        int a=listKasir.size()-1;
        int no =Integer.parseInt(listKasir.get(a).getId_kasir().replace("K-", ""))+1;
        fieldIDKasir.setText("K-"+no);
        fieldIDKasir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKasir = new javax.swing.JTable();
        buttonTambahKasir = new javax.swing.JButton();
        buttonSimpanKasir = new javax.swing.JButton();
        buttonHapusKair = new javax.swing.JButton();
        buttonEditKasir = new javax.swing.JButton();
        buttonKeluarKasir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldAlamatKasir = new javax.swing.JTextField();
        fieldUsernameKasir = new javax.swing.JTextField();
        fieldPasswordKasir = new javax.swing.JTextField();
        fieldNamaKasir = new javax.swing.JTextField();
        fieldIDKasir = new javax.swing.JTextField();
        cariKasir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("                                DATA KASIR");

        tableKasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKasirMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKasir);

        buttonTambahKasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Tambah.png"))); // NOI18N
        buttonTambahKasir.setText("Tambah");
        buttonTambahKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahKasirActionPerformed(evt);
            }
        });

        buttonSimpanKasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Simpan.png"))); // NOI18N
        buttonSimpanKasir.setText("Simpan");
        buttonSimpanKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanKasirActionPerformed(evt);
            }
        });

        buttonHapusKair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Hapus2.png"))); // NOI18N
        buttonHapusKair.setText("Hapus");
        buttonHapusKair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusKairActionPerformed(evt);
            }
        });

        buttonEditKasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Edit.png"))); // NOI18N
        buttonEditKasir.setText("Edit");
        buttonEditKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditKasirActionPerformed(evt);
            }
        });

        buttonKeluarKasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Keluar2.png"))); // NOI18N
        buttonKeluarKasir.setText("Keluar");
        buttonKeluarKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarKasirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("ID Kasir");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Nama");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Alamat");

        fieldAlamatKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAlamatKasirActionPerformed(evt);
            }
        });

        cariKasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Cari2.png"))); // NOI18N
        cariKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariKasirActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/kasir.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(fieldIDKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cariKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(fieldAlamatKasir, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                            .addComponent(fieldUsernameKasir)
                                            .addComponent(fieldNamaKasir)
                                            .addComponent(fieldPasswordKasir))))
                                .addGap(151, 151, 151)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(buttonTambahKasir)
                                .addGap(29, 29, 29)
                                .addComponent(buttonSimpanKasir)
                                .addGap(27, 27, 27)
                                .addComponent(buttonHapusKair, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonEditKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonKeluarKasir)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cariKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(fieldIDKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fieldNamaKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fieldAlamatKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fieldUsernameKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(fieldPasswordKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTambahKasir)
                    .addComponent(buttonSimpanKasir)
                    .addComponent(buttonHapusKair)
                    .addComponent(buttonEditKasir)
                    .addComponent(buttonKeluarKasir))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldAlamatKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAlamatKasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAlamatKasirActionPerformed

    private void buttonTambahKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahKasirActionPerformed
        // TODO add your handling code here:
        if(buttonTambahKasir.getText().equalsIgnoreCase("tambah")){
            buttonTambahKasir.setText("Batal");
            bersih();
            siapIsi(true);
            buatId_Kasir();     
            fieldNamaKasir.requestFocus();
            buttonTambahKasir.setEnabled(true);
            buttonSimpanKasir.setEnabled(true);
            buttonKeluarKasir.setEnabled(false);
            buttonHapusKair.setEnabled(false);
            buttonEditKasir.setEnabled(false);
            cariKasir.setEnabled(false);
        } else{
            buttonTambahKasir.setText("Tambah");
            bersih();
            siapIsi(false);
            tombolNormal();
        }
    }//GEN-LAST:event_buttonTambahKasirActionPerformed

    private void buttonSimpanKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanKasirActionPerformed
        // TODO add your handling code here:
        if(fieldNamaKasir.getText().isEmpty() ||fieldUsernameKasir.getText().isEmpty()||fieldPasswordKasir.getText().isEmpty()||fieldAlamatKasir.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Inputkan semua data kasir","TFBE",JOptionPane.INFORMATION_MESSAGE);
        } else{
            eb.setId_kasir(fieldIDKasir.getText());
            eb.setNama_kasir(fieldNamaKasir.getText());
            eb.setUsername(fieldUsernameKasir.getText());
            eb.setPassword(fieldPasswordKasir.getText());
            eb.setAlamat(fieldAlamatKasir.getText());
            
            if(buttonTambahKasir.getText().equalsIgnoreCase("batal")){
                if(bc.tambahKasir(eb)==1){
                    JOptionPane.showMessageDialog(null, "Simpan data berhasil","TFBE",JOptionPane.INFORMATION_MESSAGE);
                } else{
                    JOptionPane.showMessageDialog(null, "Simpan data gagal, periksa kembali","TFBE",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            if(buttonEditKasir.getText().equalsIgnoreCase("batal")){
                if(bc.editKasir(eb)==1){
                    JOptionPane.showMessageDialog(null, "Edit data berhasil","TFBE",JOptionPane.INFORMATION_MESSAGE);
                } else{
                    JOptionPane.showMessageDialog(null, "Edit data gagal, periksa kembali","TFBE",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            bersih();
            siapIsi(false);
            buttonTambahKasir.setText("Tambah");
            buttonEditKasir.setText("Edit");
            tombolNormal();
            showTabel();
        }
    }//GEN-LAST:event_buttonSimpanKasirActionPerformed

    private void buttonHapusKairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusKairActionPerformed
        // TODO add your handling code here:
        eb.setId_kasir(fieldIDKasir.getText());
        int pesan=JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus ?","Konfirmasi",JOptionPane.YES_NO_OPTION
                ,JOptionPane.QUESTION_MESSAGE);
        if(pesan==JOptionPane.YES_OPTION){
            if(bc.deleteKasir(eb)==1){
                JOptionPane.showMessageDialog(null, "Hapus data sukses");
                bersih();
                siapIsi(false);
                tombolNormal();
                showTabel();
            } else{
                JOptionPane.showMessageDialog(null, "Hapus data gagal");
            }
        }
    }//GEN-LAST:event_buttonHapusKairActionPerformed

    private void buttonEditKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditKasirActionPerformed
        // TODO add your handling code here:
        if(buttonEditKasir.getText().equalsIgnoreCase("edit")){
            buttonEditKasir.setText("Batal");
            siapIsi(true);
            fieldIDKasir.setEnabled(false);
            fieldNamaKasir.requestFocus();
            buttonTambahKasir.setEnabled(false);
            buttonSimpanKasir.setEnabled(true);
            buttonHapusKair.setEnabled(false);
            buttonEditKasir.setEnabled(true);
            buttonKeluarKasir.setEnabled(false);
            cariKasir.setEnabled(false);
        } else{
            buttonEditKasir.setText("Edit");
            bersih();
            siapIsi(false);
            tombolNormal();
        }
    }//GEN-LAST:event_buttonEditKasirActionPerformed

    
    private void buttonKeluarKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarKasirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonKeluarKasirActionPerformed

    private void cariKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariKasirActionPerformed
        // TODO add your handling code here:
        String cari =null;
        cari=JOptionPane.showInputDialog("Inputkan kriteria pencarian");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        listKasir.clear();
        listKasir=bc.cariKasir(cari);       
        for(x=0;x<listKasir.size();x++){
            Object[] data=new Object[5];
            data[0]=listKasir.get(x).getId_kasir();
            data[1]=listKasir.get(x).getNama_kasir();
            data[2]=listKasir.get(x).getUsername();
            data[3]=listKasir.get(x).getPassword();
            data[4]=listKasir.get(x).getAlamat();
            model.addRow(data);
        }
    }//GEN-LAST:event_cariKasirActionPerformed

    private void tableKasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKasirMouseClicked
        // TODO add your handling code here:
        int baris = tableKasir.getSelectedRow();
        
        fieldIDKasir.setText(tableKasir.getModel().getValueAt(baris, 0).toString());
        fieldNamaKasir.setText(tableKasir.getModel().getValueAt(baris, 1).toString());
        fieldUsernameKasir.setText(tableKasir.getModel().getValueAt(baris, 2).toString());
        fieldPasswordKasir.setText(tableKasir.getModel().getValueAt(baris, 3).toString());
        fieldAlamatKasir.setText(tableKasir.getModel().getValueAt(baris, 4).toString());
        siapIsi(false);
        tombolNormal();
        buttonHapusKair.setEnabled(true);
        buttonEditKasir.setEnabled(true);
    }//GEN-LAST:event_tableKasirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               frmKasir dialog = new frmKasir(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditKasir;
    private javax.swing.JButton buttonHapusKair;
    private javax.swing.JButton buttonKeluarKasir;
    private javax.swing.JButton buttonSimpanKasir;
    private javax.swing.JButton buttonTambahKasir;
    private javax.swing.JButton cariKasir;
    private javax.swing.JTextField fieldAlamatKasir;
    private javax.swing.JTextField fieldIDKasir;
    private javax.swing.JTextField fieldNamaKasir;
    private javax.swing.JTextField fieldPasswordKasir;
    private javax.swing.JTextField fieldUsernameKasir;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableKasir;
    // End of variables declaration//GEN-END:variables
}
