/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amimarketaplikasi.GUI;

import amimarketaplikasi.Method.PemasokControl;
import amimarketaplikasi.entity.EntitasPemasok;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Disca Amelia
 */
public class frmPemasok extends javax.swing.JFrame {
    int x=0;
        private DefaultTableModel model;
        PemasokControl pc=new PemasokControl();
        EntitasPemasok ep=new EntitasPemasok();
        List <EntitasPemasok> listPemasok =new ArrayList <EntitasPemasok>();

    /**
     * Creates new form frmPemasok
     */
    public frmPemasok(java.awt.Frame parent, boolean modal) {
    
    
    initComponents();
        bersih();
        siapIsi(false);
        tombolNormal();
        buatTabel();
        showTabel();
        setLocationRelativeTo(null);
    }
    
     private void bersih(){
        fieldIdPemasok.setText(null);
        fieldnamaPemasok.setText(null);
        fieldAlamatPemasok.setText(null);
        fieldnoTelpon.setText(null);
        fieldNamaBarangP.setText(null);
        fieldJumlahBarangP.setText(null);
       
    }

    private void siapIsi(boolean a){
        fieldIdPemasok.setEnabled(a);
        fieldnamaPemasok.setEnabled(a);
        fieldAlamatPemasok.setEnabled(a);
        fieldnoTelpon.setEnabled(a);
        fieldNamaBarangP.setEnabled(a);
        fieldJumlahBarangP.setEnabled(a);
    }
    
    private void tombolNormal(){
        buttonTambahP.setEnabled(true);
        buttonSimpanP.setEnabled(false);
        buttonHapusP.setEnabled(false);
        buttonEditP.setEnabled(false);
        buttonKeluarP.setEnabled(true);
        buttonCariPemasok.setEnabled(true);
    }

    private void buatTabel(){
        model=new DefaultTableModel();
        model.addColumn("ID Pemasok");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("No.Telpon");
        model.addColumn("Nama Barang");
        model.addColumn("Jumlah Barang");
        tablePemasok.setModel(model);
    }
    
    private void showTabel (){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();    
        listPemasok.clear();        
        listPemasok =pc.tampil();        
        for(x=0;x<listPemasok.size();x++){
            Object[] data=new Object[6];
            data[0]=listPemasok.get(x).getId_pemasok();
            data[1]=listPemasok.get(x).getNama_pemasok();
            data[2]=listPemasok.get(x).getAlamat_pemasok();
            data[3]=listPemasok.get(x).getNo_telepon();
            data[4]=listPemasok.get(x).getNama_barang();
            data[5]=listPemasok.get(x).getJumlah_barang();
            model.addRow(data);            
        }        
    }

    private void setcexbox(JTable tabel, TableColumn colm){
           JCheckBox checkBox=new JCheckBox("setuju");
           colm.setCellEditor(new DefaultCellEditor(checkBox));
    }
    
    private void getData (){
        List logPemasok = new ArrayList();
        
        
    }

    private void buatId_Pemasok(){
        listPemasok = pc.tampil();
        int a=listPemasok.size()-1;
        int no =Integer.parseInt(listPemasok.get(a).getId_pemasok().replace("P-", ""))+1;
        fieldIdPemasok.setText("P-"+no);
        fieldIdPemasok.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePemasok = new javax.swing.JTable();
        buttonTambahP = new javax.swing.JButton();
        buttonHapusP = new javax.swing.JButton();
        buttonSimpanP = new javax.swing.JButton();
        buttonKeluarP = new javax.swing.JButton();
        fieldnamaPemasok = new javax.swing.JTextField();
        buttonEditP = new javax.swing.JButton();
        fieldIdPemasok = new javax.swing.JTextField();
        fieldnoTelpon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fieldAlamatPemasok = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fieldNamaBarangP = new javax.swing.JTextField();
        fieldJumlahBarangP = new javax.swing.JTextField();
        buttonCariPemasok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Nama");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Alamat");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("                          DATA PEMASOK");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("ID Pemasok");

        tablePemasok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePemasokMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePemasok);

        buttonTambahP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Tambah.png"))); // NOI18N
        buttonTambahP.setText("Tambah");
        buttonTambahP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahPActionPerformed(evt);
            }
        });

        buttonHapusP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Hapus2.png"))); // NOI18N
        buttonHapusP.setText("Hapus");
        buttonHapusP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusPActionPerformed(evt);
            }
        });

        buttonSimpanP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Simpan.png"))); // NOI18N
        buttonSimpanP.setText("Simpan");
        buttonSimpanP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanPActionPerformed(evt);
            }
        });

        buttonKeluarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Keluar2.png"))); // NOI18N
        buttonKeluarP.setText("Keluar");
        buttonKeluarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarPActionPerformed(evt);
            }
        });

        buttonEditP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Edit.png"))); // NOI18N
        buttonEditP.setText("Edit");
        buttonEditP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditPActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/pemasok.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("No.Telpon");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Jumlah Barang");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Nama Barang");

        buttonCariPemasok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Cari2.png"))); // NOI18N
        buttonCariPemasok.setText("Cari");
        buttonCariPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariPemasokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonTambahP)
                        .addGap(27, 27, 27)
                        .addComponent(buttonSimpanP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16)
                        .addComponent(buttonHapusP, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEditP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonKeluarP, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fieldIdPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonCariPemasok))
                                    .addComponent(fieldnamaPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldAlamatPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldnoTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNamaBarangP, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldJumlahBarangP, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonCariPemasok, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(fieldIdPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fieldnamaPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fieldAlamatPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(fieldnoTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fieldNamaBarangP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fieldJumlahBarangP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTambahP)
                    .addComponent(buttonSimpanP)
                    .addComponent(buttonHapusP)
                    .addComponent(buttonEditP)
                    .addComponent(buttonKeluarP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablePemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePemasokMouseClicked
        // TODO add your handling code here:
        int baris = tablePemasok.getSelectedRow();

        fieldIdPemasok.setText(tablePemasok.getModel().getValueAt(baris, 0).toString());
        fieldnamaPemasok.setText(tablePemasok.getModel().getValueAt(baris, 1).toString());
        fieldAlamatPemasok.setText(tablePemasok.getModel().getValueAt(baris, 2).toString());
        fieldnoTelpon.setText(tablePemasok.getModel().getValueAt(baris, 3).toString());
        fieldNamaBarangP.setText(tablePemasok.getModel().getValueAt(baris, 4).toString());
        fieldJumlahBarangP.setText(tablePemasok.getModel().getValueAt(baris, 5).toString());

        siapIsi(false);
        tombolNormal();
        buttonHapusP.setEnabled(true);
        buttonEditP.setEnabled(true);
    }//GEN-LAST:event_tablePemasokMouseClicked

    private void buttonTambahPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahPActionPerformed
        // TODO add your handling code here:
        if(buttonTambahP.getText().equalsIgnoreCase("tambah")){
            buttonTambahP.setText("Batal");
            bersih();
            siapIsi(true);
            buatId_Pemasok();
            fieldnamaPemasok.requestFocus();
            buttonTambahP.setEnabled(true);
            buttonSimpanP.setEnabled(true);
            buttonKeluarP.setEnabled(false);
            buttonHapusP.setEnabled(false);
            buttonEditP.setEnabled(false);
            buttonCariPemasok.setEnabled(false);
        } else{
            buttonTambahP.setText("Tambah");
            bersih();
            siapIsi(false);
            tombolNormal();
        }

    }//GEN-LAST:event_buttonTambahPActionPerformed

    private void buttonHapusPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusPActionPerformed
        // TODO add your handling code here:
        ep.setId_pemasok(fieldIdPemasok.getText());
        int pesan=JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus ?","Konfirmasi",JOptionPane.YES_NO_OPTION
            ,JOptionPane.QUESTION_MESSAGE);
        if(pesan==JOptionPane.YES_OPTION){
            if(pc.deletePemasok(ep)==1){
                JOptionPane.showMessageDialog(null, "Hapus data sukses");
                bersih();
                siapIsi(false);
                tombolNormal();
                showTabel();
            } else{
                JOptionPane.showMessageDialog(null, "Hapus data gagal");
            }
        }
    }//GEN-LAST:event_buttonHapusPActionPerformed

    private void buttonSimpanPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanPActionPerformed
        // TODO add your handling code here:
        if(fieldnamaPemasok.getText().isEmpty() ||fieldAlamatPemasok.getText().isEmpty()||fieldnoTelpon.getText().isEmpty()||fieldNamaBarangP.getText().isEmpty()|| fieldJumlahBarangP.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Inputkan semua data pemasok","TFBE",JOptionPane.INFORMATION_MESSAGE);
        } else{
            ep.setId_pemasok(fieldIdPemasok.getText());
            ep.setNama_pemasok(fieldnamaPemasok.getText());
            ep.setAlamat_pemasok(fieldAlamatPemasok.getText());
            ep.setNo_telepon(Integer.parseInt(fieldnoTelpon.getText()));
            ep.setNama_barang(fieldNamaBarangP.getText());
            ep.setJumlah_barang(Integer.parseInt(fieldJumlahBarangP.getText()));

            if(buttonTambahP.getText().equalsIgnoreCase("batal")){
                if(pc.tambahPemasok(ep)==1){
                    JOptionPane.showMessageDialog(null, "Simpan data berhasil","TFBE",JOptionPane.INFORMATION_MESSAGE);
                } else{
                    JOptionPane.showMessageDialog(null, "Simpan data gagal, periksa kembali","TFBE",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            if(buttonEditP.getText().equalsIgnoreCase("batal")){
                if(pc.editPemasok(ep)==1){
                    JOptionPane.showMessageDialog(null, "Edit data berhasil","TFBE",JOptionPane.INFORMATION_MESSAGE);
                } else{
                    JOptionPane.showMessageDialog(null, "Edit data gagal, periksa kembali","TFBE",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            bersih();
            siapIsi(false);
            buttonTambahP.setText("Tambah");
            buttonEditP.setText("Edit");
            tombolNormal();
            showTabel();
        }
    }//GEN-LAST:event_buttonSimpanPActionPerformed

    private void buttonKeluarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarPActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonKeluarPActionPerformed

    private void buttonEditPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditPActionPerformed
        // TODO add your handling code here:
        if(buttonEditP.getText().equalsIgnoreCase("edit")){
            buttonEditP.setText("Batal");
            siapIsi(true);
            fieldIdPemasok.setEnabled(false);
            fieldnamaPemasok.requestFocus();
            buttonTambahP.setEnabled(false);
            buttonSimpanP.setEnabled(true);
            buttonHapusP.setEnabled(false);
            buttonEditP.setEnabled(true);
            buttonKeluarP.setEnabled(false);
            buttonCariPemasok.setEnabled(false);
        } else{
            buttonEditP.setText("Edit");
            bersih();
            siapIsi(false);
            tombolNormal();
        }
    }//GEN-LAST:event_buttonEditPActionPerformed

    private void buttonCariPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariPemasokActionPerformed
        // TODO add your handling code here:
        String cari =null;
        cari=JOptionPane.showInputDialog("Inputkan kriteria pencarian");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        listPemasok.clear();
        listPemasok=pc.cariPemasok(cari);
        for(x=0;x<listPemasok.size();x++){
            Object[] data=new Object[6];
            data[0]=listPemasok.get(x).getId_pemasok();
            data[1]=listPemasok.get(x).getNama_pemasok();
            data[2]=listPemasok.get(x).getAlamat_pemasok();
            data[3]=listPemasok.get(x).getNo_telepon();
            data[4]=listPemasok.get(x).getNama_barang();
            data[5]=listPemasok.get(x).getJumlah_barang();
            model.addRow(data);
        }
    }//GEN-LAST:event_buttonCariPemasokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               frmPemasok dialog = new frmPemasok(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCariPemasok;
    private javax.swing.JButton buttonEditP;
    private javax.swing.JButton buttonHapusP;
    private javax.swing.JButton buttonKeluarP;
    private javax.swing.JButton buttonSimpanP;
    private javax.swing.JButton buttonTambahP;
    private javax.swing.JTextField fieldAlamatPemasok;
    private javax.swing.JTextField fieldIdPemasok;
    private javax.swing.JTextField fieldJumlahBarangP;
    private javax.swing.JTextField fieldNamaBarangP;
    private javax.swing.JTextField fieldnamaPemasok;
    private javax.swing.JTextField fieldnoTelpon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePemasok;
    // End of variables declaration//GEN-END:variables
}
