/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MasterBarang.java
 *
 * Created on 20 Feb 13, 0:12:24
 */

package amimarketaplikasi.GUI;

import amimarketaplikasi.Method.BarangControl;
import amimarketaplikasi.Method.ReportControl;
import amimarketaplikasi.entity.EntitasBarang;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;


/**
 *
 * @author ONE-System
 */
public class MasterBarang extends javax.swing.JDialog {
        int x=0;
        private DefaultTableModel model;
        BarangControl bc=new BarangControl();
        EntitasBarang eb=new EntitasBarang();
        List <EntitasBarang> listBarang=new ArrayList<EntitasBarang>();
    /** Creates new form MasterBarang */
    public MasterBarang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bersih();
        siapIsi(false);
        tombolNormal();
        buatTabel();
        showTabelBarang();
    }

    private void bersih(){
        txtKdBrg.setText(null);
        txtNmBrg.setText(null);
        cmbSatuan.setSelectedItem(null);
        txtStok.setText(null);
        txtHarga.setText(null);
    }

    private void siapIsi(boolean a){
        txtKdBrg.setEnabled(a);
        txtNmBrg.setEnabled(a);
        cmbSatuan.setEnabled(a);
        txtStok.setEnabled(a);
        txtHarga.setEnabled(a);
    }
    
    private void tombolNormal(){
        btnTambah.setEnabled(true);
        btnSimpan.setEnabled(false);
        btnHapus.setEnabled(false);
        btnEdit.setEnabled(false);
        btnKeluar.setEnabled(true);
        btnCari.setEnabled(true);
    }

    private void buatTabel(){
        model=new DefaultTableModel();
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Satuan");
        model.addColumn("Stok");
        model.addColumn("Harga");

        tblBarang.setModel(model);
    }

    private void showTabelBarang(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();    
        listBarang.clear();        
        listBarang=bc.tampil();        
        for(x=0;x<listBarang.size();x++){
            Object[] data=new Object[5];
            data[0]=listBarang.get(x).getKdbarang();
            data[1]=listBarang.get(x).getNmbarang();
            data[2]=listBarang.get(x).getSatuan();
            data[3]=listBarang.get(x).getStok();
            data[4]=listBarang.get(x).getHarga();
            model.addRow(data);            
        }        
    }

    private void setcexbox(JTable tabel, TableColumn colm){
           JCheckBox checkBox=new JCheckBox("setuju");
           colm.setCellEditor(new DefaultCellEditor(checkBox));
    }
    
    private void getData (){
        List logBarang = new ArrayList();    
    }

    private void buatKdBarang(){
        listBarang=bc.tampil();
        int a=listBarang.size()-1;
        int no=Integer.parseInt(listBarang.get(a).getKdbarang().replace("B-", ""))+1;
        txtKdBrg.setText("B-"+no);
        txtKdBrg.setEnabled(false);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNmBrg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbSatuan = new javax.swing.JComboBox();
        txtStok = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        txtKdBrg = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data Barang");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Kode Barang");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(30, 80, 80, 17);

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Tambah.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnTambah);
        btnTambah.setBounds(10, 440, 100, 25);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nama Barang");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(30, 110, 90, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Satuan");
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(30, 140, 70, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Stok");
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(30, 170, 60, 17);

        txtNmBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNmBrgActionPerformed(evt);
            }
        });
        jLayeredPane1.add(txtNmBrg);
        txtNmBrg.setBounds(120, 110, 180, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Harga");
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(30, 200, 70, 17);

        cmbSatuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pcs", "Box", "Lusin" }));
        cmbSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSatuanActionPerformed(evt);
            }
        });
        jLayeredPane1.add(cmbSatuan);
        cmbSatuan.setBounds(120, 140, 120, 20);

        txtStok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStokKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStokKeyTyped(evt);
            }
        });
        jLayeredPane1.add(txtStok);
        txtStok.setBounds(120, 170, 120, 20);

        txtHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHargaKeyTyped(evt);
            }
        });
        jLayeredPane1.add(txtHarga);
        txtHarga.setBounds(120, 200, 180, 20);

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Simpan.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnSimpan);
        btnSimpan.setBounds(130, 440, 100, 25);

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Hapus2.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnHapus);
        btnHapus.setBounds(250, 440, 100, 25);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnEdit);
        btnEdit.setBounds(360, 440, 90, 25);

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Keluar2.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnKeluar);
        btnKeluar.setBounds(470, 440, 83, 25);

        txtKdBrg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLayeredPane1.add(txtKdBrg);
        txtKdBrg.setBounds(120, 80, 130, 20);

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Cari2.png"))); // NOI18N
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnCari);
        btnCari.setBounds(260, 80, 40, 20);

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        jLayeredPane1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 250, 540, 180);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("  DATA BARANG");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(190, 20, 188, 29);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/barang1.png"))); // NOI18N
        jLayeredPane1.add(jLabel9);
        jLabel9.setBounds(340, 80, 100, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(574, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        // TODO add your handling code here:
        int baris = tblBarang.getSelectedRow();
        txtKdBrg.setText(tblBarang.getModel().getValueAt(baris, 0).toString());
        txtNmBrg.setText(tblBarang.getModel().getValueAt(baris, 1).toString());
        cmbSatuan.setSelectedItem(tblBarang.getModel().getValueAt(baris, 2).toString());
        txtStok.setText(tblBarang.getModel().getValueAt(baris, 3).toString());
        txtHarga.setText(tblBarang.getModel().getValueAt(baris, 4).toString());
        siapIsi(false);
        tombolNormal();
        btnHapus.setEnabled(true);
        btnEdit.setEnabled(true);
    }//GEN-LAST:event_tblBarangMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String cari=null;
        cari=JOptionPane.showInputDialog("Inputkan kriteria pencarian");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        listBarang.clear();
        listBarang=bc.cariBarang(cari);
        for(x=0;x<listBarang.size();x++){
            Object[] data=new Object[5];
            data[0]=listBarang.get(x).getKdbarang();
            data[1]=listBarang.get(x).getNmbarang();
            data[2]=listBarang.get(x).getSatuan();
            data[3]=listBarang.get(x).getStok();
            data[4]=listBarang.get(x).getHarga();
            model.addRow(data);
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if(btnEdit.getText().equalsIgnoreCase("edit")){
            btnEdit.setText("Batal");
            siapIsi(true);
            txtKdBrg.setEnabled(false);
            txtNmBrg.requestFocus();
            btnTambah.setEnabled(false);
            btnSimpan.setEnabled(true);
            btnHapus.setEnabled(false);
            btnEdit.setEnabled(true);
            btnKeluar.setEnabled(false);
            btnCari.setEnabled(false);
        } else{
            btnEdit.setText("Edit");
            bersih();
            siapIsi(false);
            tombolNormal();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        eb.setKdbarang(txtKdBrg.getText());
        int pesan=JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus ?","Konfirmasi",JOptionPane.YES_NO_OPTION
            ,JOptionPane.QUESTION_MESSAGE);
        if(pesan==JOptionPane.YES_OPTION){
            if(bc.deleteBarang(eb)==1){
                JOptionPane.showMessageDialog(null, "Hapus data sukses");
                bersih();
                siapIsi(false);
                tombolNormal();
                showTabelBarang();
            } else{
                JOptionPane.showMessageDialog(null, "Hapus data gagal");
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(txtNmBrg.getText().isEmpty() || cmbSatuan.getSelectedItem().equals("") ||txtStok.getText().isEmpty()||txtHarga.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Inputkan semua data barang","Ami Market",JOptionPane.INFORMATION_MESSAGE);
        } else{
            eb.setKdbarang(txtKdBrg.getText());
            eb.setNmbarang(txtNmBrg.getText());
            eb.setSatuan(cmbSatuan.getSelectedItem().toString());
            eb.setStok(Integer.parseInt(txtStok.getText()));
            eb.setHarga(Integer.parseInt(txtHarga.getText()));
            if(btnTambah.getText().equalsIgnoreCase("batal")){
                if(bc.tambahBarang(eb)==1){
                    JOptionPane.showMessageDialog(null, "Simpan data berhasil","Ami Market",JOptionPane.INFORMATION_MESSAGE);
                } else{
                    JOptionPane.showMessageDialog(null, "Simpan data gagal, periksa kembali","Ami Market",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            if(btnEdit.getText().equalsIgnoreCase("batal")){
                if(bc.editBarang(eb)==1){
                    JOptionPane.showMessageDialog(null, "Edit data berhasil","Ami Market",JOptionPane.INFORMATION_MESSAGE);
                } else{
                    JOptionPane.showMessageDialog(null, "Edit data gagal, periksa kembali","Ami Market",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            bersih();
            siapIsi(false);
            btnTambah.setText("Tambah");
            btnEdit.setText("Edit");
            tombolNormal();
            showTabelBarang();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && txtHarga.getText().length() < 15
            || (c == KeyEvent.VK_BACK_SPACE)
            || (c == KeyEvent.VK_DELETE )|| (c==KeyEvent.VK_ENTER))) {
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_txtHargaKeyTyped

    private void txtStokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStokKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && txtStok.getText().length() < 3
            || (c == KeyEvent.VK_BACK_SPACE)
            || (c == KeyEvent.VK_DELETE )|| (c==KeyEvent.VK_ENTER))) {
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_txtStokKeyTyped

    private void txtStokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStokKeyPressed
        // TODO add your handling code here:
        // NumberFormat rubah=NumberFormat.getInstance();
        //  rubah.setMaximumFractionDigits(3);
        //rubah.setGroupingUsed(true);
        // txtStok.setText(rubah.format(Integer.parseInt(txtStok.getText())));
    }//GEN-LAST:event_txtStokKeyPressed

    private void txtNmBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNmBrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNmBrgActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        if(btnTambah.getText().equalsIgnoreCase("tambah")){
            btnTambah.setText("Batal");
            bersih();
            siapIsi(true);
            buatKdBarang();
            txtNmBrg.requestFocus();
            btnTambah.setEnabled(true);
            btnSimpan.setEnabled(true);
            btnHapus.setEnabled(false);
            btnEdit.setEnabled(false);
            btnKeluar.setEnabled(false);
            btnCari.setEnabled(false);
        } else{
            btnTambah.setText("Tambah");
            bersih();
            siapIsi(false);
            tombolNormal();
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void cmbSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSatuanActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MasterBarang dialog = new MasterBarang(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox cmbSatuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKdBrg;
    private javax.swing.JTextField txtNmBrg;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables

}
