/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pembelian.java
 *
 * Created on 09 Mar 13, 8:55:20
 */

package amimarketaplikasi.GUI;

import amimarketaplikasi.Method.BarangControl;
import amimarketaplikasi.Method.BeliControl;
import amimarketaplikasi.Method.DetailBeliControl;
import amimarketaplikasi.Method.ReportControl;
import amimarketaplikasi.entity.EntitasBarang;
import amimarketaplikasi.entity.EntitasBeli;
import amimarketaplikasi.entity.EntitasDetailBeli;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Dlc
 */
public class Pembelian extends javax.swing.JFrame {

    /** Creates new form  */
    public Pembelian() {
        initComponents();
        bersih();
        siapIsi(false);
        tombolNormal();
        txtStok.setVisible(false);

        DateFormat tgl=new SimpleDateFormat("dd/MMMM/yyyy");
        String htgl=tgl.format(Calendar.getInstance().getTime());
        txtTgl.setText(htgl);
    }

 private void bersih(){
        txtNota.setText(null);
        txtKdBrg.setText(null);
        txtNmBrg.setText(null);
        txtHarga.setText(null);
        txtJml.setText(null);
        txtTotal.setText("0");
        txtBayar.setText("0");
        txtKembali.setText("0");
    }

    private void siapIsi(boolean a){
        txtTgl.setEnabled(a);
        txtNota.setEnabled(a);
        txtKdBrg.setEnabled(a);
        txtNmBrg.setEnabled(a);
        txtHarga.setEnabled(a);
        txtJml.setEnabled(a);
        txtTotal.setEnabled(a);
        txtBayar.setEnabled(a);
        txtKembali.setEnabled(a);
    }

    private void tombolNormal(){
        btnTambah.setEnabled(true);
        btnSimpan.setEnabled(false);
        btnTambahBrg.setEnabled(false);
        btnKurangBrg.setEnabled(false);
        btnCariBrg.setEnabled(false);
    }

    private void buatTabelBeli(){
        model=new DefaultTableModel();
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga");
        model.addColumn("Jumlah");
        model.addColumn("Total");
        tblBarang.setModel(model);
    }


    private void tampilBarang(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        listEDB.clear();
        listEDB=dbc.tampilBarang(txtNota.getText());
        for(int x=0;x<listEDB.size();x++){
            Object[] data=new Object[5];
            data[0]=listEDB.get(x).getKdbarang();
            data[1]=listEDB.get(x).getNmbarang();
            data[2]=listEDB.get(x).getHarga();
            data[3]=listEDB.get(x).getJml();
            data[4]=listEDB.get(x).getTotal();
            model.addRow(data);
        }
    }

    private void buatNoNota(){
        listEb=bc.tampil();
        if(listEb.isEmpty()){
            txtNota.setText("N-1");
        } else{
        int a=listEb.size()-1;
        int no=Integer.parseInt(listEb.get(a).getNonota().replace("N-", ""))+1;
        txtNota.setText("N-"+no);
        txtNota.setEnabled(false);
        }
    }

    private void buatTabelBarang(){
        model=new DefaultTableModel();
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Satuan");
        model.addColumn("Stok");
        model.addColumn("Harga");
        tblMasterBarang.setModel(model);
    }

    private void showTabelBarang(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        listBarang.clear();
        listBarang=brgc.tampil();
        for(int x=0;x<listBarang.size();x++){
            Object[] data=new Object[5];
            data[0]=listBarang.get(x).getKdbarang();
            data[1]=listBarang.get(x).getNmbarang();
            data[2]=listBarang.get(x).getSatuan();
            data[3]=listBarang.get(x).getStok();
            data[4]=listBarang.get(x).getHarga();
            model.addRow(data);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmBarang = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMasterBarang = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtCariBrg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtKdBrg = new javax.swing.JTextField();
        txtNmBrg = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtJml = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtBayar = new javax.swing.JTextField();
        txtKembali = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnTambahBrg = new javax.swing.JButton();
        btnKurangBrg = new javax.swing.JButton();
        btnCariBrg = new javax.swing.JButton();
        txtTgl = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buttonHitung = new javax.swing.JButton();

        frmBarang.setTitle("Master Data Barang");

        tblMasterBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMasterBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMasterBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMasterBarang);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Data Barang");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ketikan Kriteria Pencarian [ENTER]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txtCariBrg.setText("jTextField1");
        txtCariBrg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariBrgKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Pilih.gif"))); // NOI18N
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(txtCariBrg, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCariBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frmBarangLayout = new javax.swing.GroupLayout(frmBarang.getContentPane());
        frmBarang.getContentPane().setLayout(frmBarangLayout);
        frmBarangLayout.setHorizontalGroup(
            frmBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frmBarangLayout.setVerticalGroup(
            frmBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmBarangLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("  DATA BARANG");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transaksi Pembelian Barang");
        setResizable(false);

        jLabel2.setText("No Nota");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(20, 70, 60, 14);

        jLabel3.setText("Tanggal");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(470, 70, 60, 14);

        jLabel5.setText("Kode Barang");
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(20, 150, 90, 14);

        jLabel6.setText("Nama Barang");
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(130, 150, 100, 14);
        jLayeredPane1.add(txtNota);
        txtNota.setBounds(80, 70, 90, 20);

        jLabel7.setText("Harga");
        jLayeredPane1.add(jLabel7);
        jLabel7.setBounds(410, 150, 60, 14);

        jLabel8.setText("Jumlah");
        jLayeredPane1.add(jLabel8);
        jLabel8.setBounds(520, 150, 50, 14);
        jLayeredPane1.add(txtKdBrg);
        txtKdBrg.setBounds(20, 170, 70, 20);
        jLayeredPane1.add(txtNmBrg);
        txtNmBrg.setBounds(129, 170, 270, 20);
        jLayeredPane1.add(txtHarga);
        txtHarga.setBounds(410, 170, 100, 20);

        txtJml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJmlKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJmlKeyTyped(evt);
            }
        });
        jLayeredPane1.add(txtJml);
        txtJml.setBounds(520, 170, 50, 20);

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        jLayeredPane1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 240, 680, 180);

        jLabel9.setBackground(new java.awt.Color(255, 102, 102));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Total");
        jLayeredPane1.add(jLabel9);
        jLabel9.setBounds(30, 430, 70, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Bayar");
        jLayeredPane1.add(jLabel10);
        jLabel10.setBounds(20, 460, 80, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Kembali");
        jLayeredPane1.add(jLabel11);
        jLabel11.setBounds(20, 520, 90, 14);

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtTotal.setForeground(java.awt.Color.red);
        jLayeredPane1.add(txtTotal);
        txtTotal.setBounds(120, 430, 140, 20);

        txtBayar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtBayar.setForeground(java.awt.Color.red);
        txtBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBayarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBayarKeyTyped(evt);
            }
        });
        jLayeredPane1.add(txtBayar);
        txtBayar.setBounds(120, 460, 140, 20);

        txtKembali.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtKembali.setForeground(java.awt.Color.red);
        txtKembali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKembaliKeyTyped(evt);
            }
        });
        jLayeredPane1.add(txtKembali);
        txtKembali.setBounds(120, 520, 140, 20);

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Tambah.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnTambah);
        btnTambah.setBounds(20, 210, 100, 25);

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amimarketaplikasi/Gambar/Simpan.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnSimpan);
        btnSimpan.setBounds(290, 510, 110, 25);

        btnTambahBrg.setText("+");
        btnTambahBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBrgActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnTambahBrg);
        btnTambahBrg.setBounds(580, 170, 60, 23);

        btnKurangBrg.setText("-");
        btnKurangBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurangBrgActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnKurangBrg);
        btnKurangBrg.setBounds(640, 170, 60, 23);

        btnCariBrg.setText("...");
        btnCariBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariBrgActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnCariBrg);
        btnCariBrg.setBounds(90, 170, 30, 23);
        jLayeredPane1.add(txtTgl);
        txtTgl.setBounds(520, 70, 170, 20);
        jLayeredPane1.add(txtStok);
        txtStok.setBounds(520, 110, 40, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("TRANSAKSI PENJUALAN");
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(220, 20, 320, 29);

        buttonHitung.setText("Hitung");
        buttonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHitungActionPerformed(evt);
            }
        });
        jLayeredPane1.add(buttonHitung);
        buttonHitung.setBounds(120, 490, 90, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(733, 634));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtJmlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJmlKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && txtJml.getText().length() < 4
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE )|| (c==KeyEvent.VK_ENTER))) {
            getToolkit().beep();
            evt.consume();
        }
}//GEN-LAST:event_txtJmlKeyTyped

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBarangMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        if(btnTambah.getText().equalsIgnoreCase("tambah")){
            btnTambah.setText("Batal");
            siapIsi(true);
            bersih();
            buatNoNota();
            
            btnSimpan.setEnabled(true);
            btnTambahBrg.setEnabled(true);
            btnKurangBrg.setEnabled(true);
            btnCariBrg.setEnabled(true);
        }else{
            bersih();
            siapIsi(false);
            btnTambah.setText("Tambah");
            tombolNormal();
        }
}//GEN-LAST:event_btnTambahActionPerformed

    private void btnCariBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariBrgActionPerformed
        // TODO add your handling code here:
        buatTabelBarang();
        showTabelBarang();
        txtCariBrg.setText(null);
        //frmBarang.setSize(472,390);
        frmBarang.setBounds(300, 300, 472, 390);
        frmBarang.setVisible(true);
        txtCariBrg.requestFocus();
}//GEN-LAST:event_btnCariBrgActionPerformed

    private void txtCariBrgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariBrgKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        listBarang.clear();
        listBarang=brgc.cariBarang(txtCariBrg.getText());
        for(int x=0;x<listBarang.size();x++){
            Object[] data=new Object[5];
            data[0]=listBarang.get(x).getKdbarang();
            data[1]=listBarang.get(x).getNmbarang();
            data[2]=listBarang.get(x).getSatuan();
            data[3]=listBarang.get(x).getStok();
            data[4]=listBarang.get(x).getHarga();
            model.addRow(data);
        }
        }
    }//GEN-LAST:event_txtCariBrgKeyPressed

    private void tblMasterBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMasterBarangMouseClicked
        // TODO add your handling code here:
        int baris = tblMasterBarang.getSelectedRow();
        txtKdBrg.setText(tblMasterBarang.getModel().getValueAt(baris, 0).toString());
        txtNmBrg.setText(tblMasterBarang.getModel().getValueAt(baris, 1).toString());
        txtStok.setText(tblMasterBarang.getModel().getValueAt(baris, 3).toString());
        txtHarga.setText(tblMasterBarang.getModel().getValueAt(baris, 4).toString());
        txtJml.requestFocus();
        frmBarang.setVisible(false);
    }//GEN-LAST:event_tblMasterBarangMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        listBarang.clear();
        listBarang=brgc.cariBarang(txtCariBrg.getText());
        for(int x=0;x<listBarang.size();x++){
            Object[] data=new Object[5];
            data[0]=listBarang.get(x).getKdbarang();
            data[1]=listBarang.get(x).getNmbarang();
            data[2]=listBarang.get(x).getSatuan();
            data[3]=listBarang.get(x).getStok();
            data[4]=listBarang.get(x).getHarga();
            model.addRow(data);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTambahBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBrgActionPerformed
        // TODO add your handling code here:
        if(txtKdBrg.getText().equals("") || txtNota.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi inputan pembelian barang");
        } else{
             int jml=Integer.parseInt(txtJml.getText());
             int stok=Integer.parseInt(txtStok.getText());
             if(jml>stok){
                JOptionPane.showMessageDialog(null, "Stok barang tidak mencukupi");
             }else{
                listEDB=dbc.CekBarang(txtNota.getText(), txtKdBrg.getText());
                if(listEDB.size()>0){
                    JOptionPane.showMessageDialog(null, "Barang ini sudah anda beli, silahkan pilih yang lain");
                } else{
                    int harga=Integer.parseInt(txtHarga.getText());
                    EntitasDetailBeli edb=new EntitasDetailBeli();
                    edb.setNonota(txtNota.getText());
                    edb.setKdbarang(txtKdBrg.getText());
                    edb.setNmbarang(txtNmBrg.getText());
                    edb.setHarga(harga);
                    edb.setJml(jml);
                    edb.setTotal(harga*jml);                    
                    if (dbc.tambahDetailBeli(edb)==0){
                        JOptionPane.showMessageDialog(null, "Simpan detail data barang gagal, Mohon periksa kembali");
                    } else{
                        int sisaStok=stok-jml;
                        brgc.updateStok(sisaStok, txtKdBrg.getText());
                        buatTabelBeli();
                        tampilBarang();
                        int total=Integer.parseInt(txtTotal.getText());
                        int totalBayar=total+(harga*jml);
                        txtTotal.setText(Integer.toString(totalBayar));
                        
                        txtKdBrg.setText("");
                        txtNmBrg.setText("");
                        txtHarga.setText("");
                        txtJml.setText("");
                        txtStok.setText("");                        
                    }
                }
             }
        }

    }//GEN-LAST:event_btnTambahBrgActionPerformed

    private void txtJmlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJmlKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtJmlKeyPressed

    private void btnKurangBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurangBrgActionPerformed
        // TODO add your handling code here:
        int jmlbaris=tblBarang.getRowCount();
        int baris = tblBarang.getSelectedRow();
        if(jmlbaris==0){
            JOptionPane.showMessageDialog(null, "Tidak ada barang yang dibeli");
        } else{
            listBarang=brgc.cariBarangDenganKode(tblBarang.getModel().getValueAt(baris, 0).toString());
            int stok=listBarang.get(0).getStok();
            int jml=Integer.parseInt(tblBarang.getModel().getValueAt(baris, 3).toString());
            int sisaStok=stok+jml;
            brgc.updateStok(sisaStok, tblBarang.getModel().getValueAt(baris, 0).toString());

            int total=Integer.parseInt(txtTotal.getText());
            int totalBarang=Integer.parseInt(tblBarang.getModel().getValueAt(baris, 4).toString());
            int totalBayar=total-totalBarang;
            txtTotal.setText(Integer.toString(totalBayar));
            dbc.deleteDetailBeli(txtNota.getText(), tblBarang.getModel().getValueAt(baris, 0).toString());
            buatTabelBeli();
            tampilBarang();
            
        }
    }//GEN-LAST:event_btnKurangBrgActionPerformed

    private void txtBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBayarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
        int total=Integer.parseInt(txtTotal.getText());
        int bayar=Integer.parseInt(txtBayar.getText());
            if(bayar<total){
                JOptionPane.showMessageDialog(null, "Jumlah bayar tidak mencukupi");
                txtBayar.requestFocus();
            } else{
                int kembali=bayar-total;
                txtKembali.setText(Integer.toString(kembali));
            }
        }
    }//GEN-LAST:event_txtBayarKeyPressed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        int baris=tblBarang.getRowCount();
        if(txtNota.getText().equals("") || txtBayar.getText().equals("0") || txtKembali.getText().equals("0")){
            JOptionPane.showMessageDialog(null, "Lengkapi inputan pembelian barang");
        } else{
            DateFormat tgl=new SimpleDateFormat("yyyy/MM/dd");
            String htgl=tgl.format(Calendar.getInstance().getTime());
            
            EntitasBeli eb=new EntitasBeli();
            eb.setNonota(txtNota.getText());
            eb.setTgl(htgl);
            eb.setBayar(Integer.parseInt(txtBayar.getText()));
            eb.setTotal(Integer.parseInt(txtTotal.getText()));
            eb.setKembali(Integer.parseInt(txtKembali.getText()));
            if(bc.tambahBeli(eb)==1){
               int pesan=JOptionPane.showConfirmDialog(null, "Cetak Kwitansi Nota","Cetak",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
               if(pesan==JOptionPane.YES_OPTION){
                   ReportControl rc=new ReportControl();
                   rc.cetakNota(txtNota.getText());
               } else {
                   JOptionPane.showMessageDialog(null, "Simpan Transaksi Berhasil");
               }
                bersih();
                siapIsi(false);
                btnTambah.setText("Tambah");
                btnSimpan.setEnabled(false);
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
            } else{
                JOptionPane.showMessageDialog(null, "Simpan transaksi pembelian gagal");
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtBayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBayarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && txtJml.getText().length() < 4
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE )|| (c==KeyEvent.VK_ENTER))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtBayarKeyTyped

    private void txtKembaliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKembaliKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && txtJml.getText().length() < 4
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE )|| (c==KeyEvent.VK_ENTER))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtKembaliKeyTyped

    private void buttonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHitungActionPerformed
        // TODO add your handling code here:
        int total=Integer.parseInt(txtTotal.getText());
        int bayar=Integer.parseInt(txtBayar.getText());
            if(bayar<total){
                JOptionPane.showMessageDialog(null, "Jumlah bayar tidak mencukupi");
                txtBayar.requestFocus();
            } else{
                int kembali=bayar-total;
                txtKembali.setText(Integer.toString(kembali));
            }
        

        
    }//GEN-LAST:event_buttonHitungActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariBrg;
    private javax.swing.JButton btnKurangBrg;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambahBrg;
    private javax.swing.JButton buttonHitung;
    private javax.swing.JDialog frmBarang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTable tblMasterBarang;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtCariBrg;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJml;
    private javax.swing.JTextField txtKdBrg;
    private javax.swing.JTextField txtKembali;
    private javax.swing.JTextField txtNmBrg;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtTgl;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
private DefaultTableModel model;
DetailBeliControl dbc=new DetailBeliControl();
BeliControl bc=new BeliControl();
BarangControl brgc=new BarangControl();
List <EntitasBeli> listEb=new ArrayList<EntitasBeli>();
List <EntitasDetailBeli> listEDB=new ArrayList<EntitasDetailBeli>();
List <EntitasBarang> listBarang=new ArrayList<EntitasBarang>();
}
